apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake
  template:
    metadata:
      labels:
        app: snake
    spec:
      #restartPolicy: OnFailur
      #hostPID: true
      #hostNetwork: true
      containers:
      - name: snake
        image: docker.io/kelysa/snake:lastest
        command: ['sh', '-c', './public/bin/env.sh > public/env.sh']
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_BOOT
              - SYS_TIME
              - KILL
        imagePullPolicy: Always
        env:  
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        #ports:
        #- containerPort: 3000
        resources:
          limits:
            cpu: "60"
          requests:
            cpu: 10m
              #volumes:
              #- name: snake-pv-claim
              #persistentVolumeClaim:
              #claimName: snake-pv-claim
